name: Build, Test and Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup node 12.x
      uses: actions/setup-node@v2.4.0
      with:
        node-version: 12.x
    
    - name: Install
      run: yarn

    - name: Gatsby Publish
      if: success()
      uses: enriikke/gatsby-gh-pages-action@v2.2.0
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
